config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  root 'home#index'

  resources :heroes do
    resources :rel_hero_divides do
      resources :item_sets do
        resources :rel_set_items
      end
    end
    resources :rel_hero_grown_levels
    resources :skills
  end

  resources :divides do
    resources :rel_hero_divides
  end

  resources :blogs

  resources :items
  resources :banners
  get '/:format/items', :to => 'items#index'
  get '/:format/blogs', :to => 'blogs#index'

end

app/views/layouts/_footer.html.erb
<footer class="text-center">This Bootstrap 3 dashboard layout is compliments of <a href="http://www.bootply.com/85850"><strong>Bootply.com</strong></a></footer>

app/views/layouts/_header.html.erb
<div id="top-nav" class="navbar navbar-inverse navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-toggle"></span>
      </button>
      <span class="glyphicon glyphicon-th-list avbar-brand toggleMenu" id="magicCollapse" data-form="1"></span>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">

        <li class="dropdown">
          <a class="dropdown-toggle" role="button" data-toggle="dropdown" href="#">
            <i class="glyphicon glyphicon-user"></i> <%= current_user.user_name %> <span class="caret"></span></a>
          <ul id="g-account-menu" class="dropdown-menu" role="menu">
            <li><%= link_to "個人情報管理", edit_user_path(current_user) %></li>
            <li>
              <%= link_to '<i class="glyphicon glyphicon-lock"></i>ログアウト'.html_safe, destroy_user_session_path, :method => :delete %>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </div><!-- /container -->
</div>
<!-- /Header -->

app/views/layouts/_modal.html.erb
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">List</h4>
      </div>
      <div class="modal-body">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<div class="col-md-3" id="navigation">
  <ul class="nav nav-stacked">
    <li>
      <%= link_to '<i class="glyphicon glyphicon-flash"></i><span class="text"> ヒーロー管理</span>'.html_safe, heroes_path %>
    </li>
    <li>
      <%= link_to '<i class="glyphicon glyphicon-list-alt"></i><span class="text"> アイテム管理</span>'.html_safe, items_path %>
    </li>
    <li>
      <%= link_to '<i class="glyphicon glyphicon-th"></i><span class="text"> ブログ管理</span>'.html_safe, blogs_path %>
    </li>
    <li>
      <%= link_to '<i class="glyphicon glyphicon-picture"></i><span class="text"> バーナー管理</span>'.html_safe, banners_path %>
    </li>
  </ul>
  <hr>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dota</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if current_user %>
    <%= render "layouts/header" %>
    <!-- Main -->
    <div class="container">
      <div class="row">
        <%= render "layouts/navigation" %>
        <div class="col-md-9" id="mainContent">
          <%= yield %>
        </div>
      </div>
    </div><!--/container-->
  <% else %>
    <%= yield %>
  <% end %>

</body>
</html>